### ISSUE TITLE
Integrate hexops best-pracitces

### ISSUE THREAD

**Issue by dboitnot** [sig-docker/tomcat#15]
Consider adding a build which follows these recommendations:

https://github.com/hexops/dockerfile

- [x] Non-root user with static uid/gid - #16 
- [x] tini as ENTRYPOINT - #17 
- [x] Arguments in CMD - #18

**Comment by dboitnot** [comment]
These features are published starting with build 444.

- #16 (Non-root) is available through the `-hardened` suffix
- #17 (tini) is available through `-tini` and `-hardened`
- #18 (arguments in CMD) is in all builds
